#!/bin/bash

set -e

function err() {
    echo $* >&2
    exit 1
}

if [[ $# != 8 ]]; then
    err "usage: $0 experiment experiment_count seed poptype genometype maxgens runid comment"
fi

pop_size=10000
experiment="$1"
experiment_count="$2"
seed="$3"
pop_type="$4"
genome_type="$5"
maxgens="$6"
runid="$7"
comment="$8"

neat_dir=$(readlink -f $(dirname $0)/..)
runs_dir=$(readlink -f $neat_dir/../runs)
run_dir=$runs_dir/$runid

if [[ -e $run_dir ]]; then
    err "Already exists: $run_dir"
fi

mkdir -p $run_dir
touch $run_dir/neat_out
rm -f $neat_dir/out
ln -s $run_dir/neat_out $neat_dir/out

echo $experiment > $run_dir/experiment_name
echo $experiment_count > $run_dir/experiment_count
echo $seed > $run_dir/rng_seed
echo $pop_type > $run_dir/pop_type
echo $genome_type > $run_dir/genome_type
echo $maxgens > $run_dir/maxgens
echo "$comment" > $run_dir/comment.txt
submit_script=$run_dir/pbs_submit.sh

cat > $submit_script <<EOF
#!/bin/sh

#PBS -N neat-$runid
#PBS -o $run_dir/pbs_out 
#PBS -e $run_dir/pbs_err

#PBS -l nodes=1:ppn=10
#PBS -q m1060

cd $neat_dir

source /share/apps/Modules/3.2.10/init/sh
module load gcc/4.9.1

make || exit 1

git log -n 5 > $run_dir/gitlog
git status > $run_dir/gitstat
hostname > $run_dir/hostname

cd $run_dir
cp -r $neat_dir/src src
time $neat_dir/neat $experiment $experiment_count $seed $pop_type $genome_type $pop_size $maxgens > neat_out
EOF

qsub $submit_script
